### PR TITLE
Create Tamil.lng

### PR DESCRIPTION
**Pull request by TamilNeram**
Added Tamil Language file in UTF8 format

### CODE REVIEW

**Comment by zmatsuo** [comment]
I'm sorry, 
I have one more request.

I've created a branch(#136) that includes commit you sent.
If I merge this, it seems the pull request will become unnecessary
and thus rejected.

Could you create a branch (such as tamil_lng)
and also include commit 0e722fe9,
and then send pull request again?

**Comment by TamilNeram** [comment]
Created a branch and added one small change and updated the pull request.

**Comment by zmatsuo** [comment]
I merged it into the main.
Thank you.

**Comment by TamilNeram** [comment]
Waiting for the next build/installer with Tamil :).

**Comment by zmatsuo** [comment]
883bee28(main branch) build binary.
https://ci.appveyor.com/project/teraterm/github-main/builds/49366974/artifacts
:)

**Pull request merged**
